package gov.njdpb.dev.filenetHlthChk; // Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;

public class FnetHlthChkTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  private JavascriptExecutor js;

  @BeforeEach
  public void setUp() {
    WebDriverManager.chromedriver().setup(); // Let Selenium manage the driver
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<>();
    driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10)); // Add implicit wait
  }

  @AfterEach
  public void tearDown() {
    if (driver != null) {
      driver.quit();
    }
  }

  private String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.getOrDefault("window_handles", Set.of());

    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
      return whNow.iterator().next();
    }
    return null; // Return null instead of throwing an error
  }

  @Test
  public void fnetHlthChk() {
    driver.get("https://ty-sblprd5-ha-e.njes.state.nj.us:1443/siebel/app/pensions/enu?SWECmd=Start");
    driver.manage().window().setSize(new Dimension(1296, 696));

    // Wait for elements to be interactable
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));

    WebElement usernameField = wait.until(ExpectedConditions.elementToBeClickable(By.id("s_swepi_1")));
    usernameField.sendKeys("sadmin");

    WebElement passwordField = driver.findElement(By.id("s_swepi_2"));
    passwordField.sendKeys("siebdev99");
    passwordField.sendKeys(Keys.ENTER);

    WebElement aabergLink = wait.until(ExpectedConditions.elementToBeClickable(By.linkText("AABERG")));
    aabergLink.click();

    vars.put("window_handles", driver.getWindowHandles());

    WebElement uiElement = wait.until(ExpectedConditions.elementToBeClickable(By.id("ui-id-154")));
    uiElement.click();

    vars.put("win6045", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());

    if (vars.get("win6045") != null) {
      driver.switchTo().window(vars.get("win6045").toString());
      driver.close();
      driver.switchTo().window(vars.get("root").toString());
    }

    WebElement tbButton = wait.until(ExpectedConditions.elementToBeClickable(By.id("tb_0")));
    tbButton.click();

    WebElement logoutButton = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".siebui-btn-logout")));
    logoutButton.click();

    driver.close();
  }
}
