name: Salesforce Document Record Creation

on:
  push:
    paths:
      - "**.docx"
      - "**.md"
      - "**.txt"
      - "**.mp4"
      - "*"

jobs:
  create_salesforce_record:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install axios @salesforce/core

      - name: Create Salesforce records
        run: node create_salesforce_record.js
        env:
          SF_CLIENT_ID: ${{ secrets.SF_CLIENT_ID }}
          SF_CLIENT_SECRET: ${{ secrets.SF_CLIENT_SECRET }}
          SF_USER_NAME: ${{ secrets.SF_USER_NAME }}
          SF_CALLBACK_URL: ${{ secrets.SF_CALLBACK_URL }}
          SF_AUTH_URL: ${{ secrets.SF_AUTH_URL }}
          SF_TOKEN_URL: ${{ secrets.SF_TOKEN_URL }}
          SF_INSTANCE_URL: ${{ secrets.SF_INSTANCE_URL }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
